### ISSUE TITLE
GatewayTest is unstable

### ISSUE THREAD

**Issue by wborn** [openremote/openremote#1416]
This test is unstable, see: https://github.com/openremote/openremote/actions/runs/10845895994/job/30097701804

```
GatewayTest > Verify gateway client service FAILED
    Condition not satisfied after 15.00 seconds and 88 attempts
        at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
        at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
        at org.***.test.gateway.GatewayTest.Verify gateway client service(GatewayTest.groovy:922)

        Caused by:
        Condition not satisfied:

        attributeEvents.size() == 4
        |               |      |
        |               6      false
        [AttributeEvent{timestamp=2024-09-13T08:42:58.723Z, ref=AttributeRef{id='7CPO7wzLhDUmzEkChL7Gi3', name='onOff'}, realm=smartcity, source=null, valueType=java.lang.Boolean}, AttributeEvent{timestamp=2024-09-13T08:42:58.723Z, ref=AttributeRef{id='YvPO7wzLhDUmzEkChL7Gi3', name='onOff'}, realm=building, source=org.***.manager.gateway.GatewayService, valueType=java.lang.Boolean}, AttributeEvent{timestamp=2024-09-13T08:42:58.728Z, ref=AttributeRef{id='3TZMc5Kg7bBGGnsqWgIVhR', name='onOff'}, realm=smartcity, source=org.***.manager.asset.AttributeLinkingService, valueType=java.lang.Boolean}, AttributeEvent{timestamp=2024-09-13T08:42:58.728Z, ref=AttributeRef{id='UMZMc5Kg7bBGGnsqWgIVhR', name='onOff'}, realm=building, source=org.***.manager.gateway.GatewayService, valueType=java.lang.Boolean}, AttributeEvent{timestamp=2024-09-13T08:42:59.041Z, ref=AttributeRef{id='YRrl4OmLxvweQLQwjGiS0L', name='agentStatus'}, realm=building, source=AgentSourceRef{id='YRrl4OmLxvweQLQwjGiS0L', name='agentStatus'}, valueType=org.***.model.asset.agent.ConnectionStatus}, AttributeEvent{timestamp=2024-09-13T08:42:59.047Z, ref=AttributeRef{id='57bq3VeEBXy9DeBDstVgZr', name='tunnelingSupported'}, realm=building, source=org.***.manager.gateway.GatewayService, valueType=java.lang.Boolean}]
            at org.***.test.gateway.GatewayTest.Verify gateway client service_closure62(GatewayTest.groovy:923)
            at org.***.test.gateway.GatewayTest.Verify gateway client service_closure62(GatewayTest.groovy)
            at app//groovy.lang.Closure.call(Closure.java:412)
            at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
            ... 2 more
```

**Comment by wborn** [comment]
See also: https://github.com/openremote/openremote/actions/runs/10883105059/job/30195517098

```
GatewayTest > Gateway asset provisioning and local manager logic test PASSED
  Test Verify gateway client service FAILED (16.9s)

  Condition not satisfied after 15.00 seconds and 76 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
      at org.***.test.gateway.GatewayTest.Verify gateway client service(GatewayTest.groovy:873)
  Caused by: Condition not satisfied:
  
  gatewayMicrophone3 != null
  |                  |
  null               false
      at org.***.test.gateway.GatewayTest.Verify gateway client service_closure57(GatewayTest.groovy:875)
      at org.***.test.gateway.GatewayTest.Verify gateway client service_closure57(GatewayTest.groovy)
      at app//groovy.lang.Closure.call(Closure.java:412)
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
      ... 2 more

org.***.test.gateway.GatewayTest > Verify gateway client service took: 16954ms

GatewayTest > Verify gateway client service FAILED
    Condition not satisfied after 15.00 seconds and 76 attempts
        at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
        at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
        at org.***.test.gateway.GatewayTest.Verify gateway client service(GatewayTest.groovy:873)

        Caused by:
        Condition not satisfied:

        gatewayMicrophone3 != null
        |                  |
        null               false
            at org.***.test.gateway.GatewayTest.Verify gateway client service_closure57(GatewayTest.groovy:875)
            at org.***.test.gateway.GatewayTest.Verify gateway client service_closure57(GatewayTest.groovy)
            at app//groovy.lang.Closure.call(Closure.java:412)
            at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
            ... 2 more
  Test Verify gateway tunnel factory SKIPPED
org.***.test.gateway.GatewayTest > Verify gateway tunnel factory took: 0ms
```
