### ISSUE TITLE
EnergyOptimisationAssetTest unstable

### ISSUE THREAD

**Issue by wborn** [openremote/openremote#1479]
It failed in this build: https://github.com/openremote/openremote/actions/runs/11701244311/job/32586940870

```
org.openremote.test.energy.EnergyOptimisationAssetTest

  Test Test storage asset with consumer and producer PASSED (14.6s)
org.openremote.test.energy.EnergyOptimisationAssetTest > Test storage asset with consumer and producer took: 14658ms

EnergyOptimisationAssetTest > Test storage asset with consumer and producer PASSED
  Test Test savings calculations FAILED (11.3s)

  Condition not satisfied after 10.00 seconds and 52 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
      at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations(EnergyOptimisationAssetTest.groovy:324)
  Caused by: Condition not satisfied:
  
  (assetStorageService.find(managerTestSetup.electricityOptimisationAssetId) as EnergyOptimisationAsset).getFinancialSaving().orElse(0d) == -1.5
   |                   |    |                |                                                           |                    |          |
   |                   |    |                3IvOesjjOSunQ9Fb0JGxoo                                      Optional[-3.0]       -3.0       false
   |                   |    <org.openremote.setup.integration.ManagerTestSetup@5560daf0 smartOfficeId=5QGtsMdpXuSY13GVGsU5P9 groundFloorId=57OsUoLq5JFoXFeM6Ct5rp lobbyId=62nnvQjlCH88DESswoCFH8 agentId=4I5tGSSMSpISpwMKsQ9Nyn thingId=6FVWhTcKFf1tdl8eiS7nFc smartBuildingId=6XbK6qOVZWRA8sJXBaWPVD apartment1Id=5B5hxiMNLyh1RQrCL8O6TC apartment1ServiceAgentId=5nh8n7vTu1t3vqPI0ZW9Oe apartment1LivingroomId=3rsAZ4SwFKUEBgtjVtlGb1 apartment1KitchenId=3Qj5AOxkvXq54HJgx983XZ apartment1HallwayId=25jN7n2vN2lVxw1QzgWZss apartment1Bedroom1Id=7jQho9CQuEQSOCC1XZTqTd apartment1BathroomId=3ArrWS0MJdSXrPCJfplIUz apartment2Id=3jm23JN24m6Yk9oviNro3f apartment3Id=7ID5AwQ361fiz71A0I7Fdh apartment2LivingroomId=5YTmK9WLhFhVvTjNEK0UGR apartment2BathroomId=4tw8tYNgDyNDKespOxzAiz apartment3LivingroomId=61lyWcvjr3pVZVeCQG5Kmc realmMasterName=master realmBuildingName=building realmCityName=smartcity realmEnergyName=energy smartCityServiceAgentId=2sxoYTEA6a1Q9GCVakQSCV area1Id=2hc2TrIJVwI54zin7wu4UX microphone1Id=5isrLjiMw2u4BXTCyYiryp peopleCounter1AssetId=76NGjk6Oyj3v0T5b6eyC10 peopleCounter2AssetId=5epDCNfCenobtr8aVakCY5 peopleCounter3AssetId=2yUunxJ1cRCYb86GdWZYaY electricityOptimisationAssetId=3IvOesjjOSunQ9Fb0JGxoo electricityConsumerAssetId=4EmmbLWs9zC8zSJ28znSNL electricitySolarAssetId=5xK5qMsDYvbyZpkirb92cS electricityWindAssetId=5OYyO9S1zYGFWgEvxkZH0r electricitySupplierAssetId=3LN9mhEfElABStV8YA2nig electricityBatteryAssetId=20wpJQkosb1NRT8Fjqkvx8 light1Id=64V8sX0sXLCp7faECIktm5 light2Id=3VpLHSuUYLWsNdsKpBkmcb provisionDocRoot=deployment/manager/provisioning timerService=TimerService{clock=PSEUDO} persistenceService=ManagerPersistenceService{database=POSTGRES, persistenceUnitName='OpenRemotePU'} identityService=ManagerIdentityService{identityProvider=ManagerKeycloakIdentityProvider{}} assetStorageService=AssetStorageService{} assetProcessingService=AssetProcessingService{} assetDatapointService=AssetDatapointService{} assetPredictedDatapointService=AssetPredictedDatapointService{} rulesetStorageService=RulesetStorageService{} setupService=SetupService{} EMPTY_META=[]>
   |                   EnergyOptimisationAsset{id='3IvOesjjOSunQ9Fb0JGxoo', name='Optimisation', type ='EnergyOptimisationAsset', parentId='null', realm='energy'}
   AssetStorageService{}
      at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure13(EnergyOptimisationAssetTest.groovy:325)
      at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure13(EnergyOptimisationAssetTest.groovy)
      at app//groovy.lang.Closure.call(Closure.java:412)
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
      ... 2 more

org.openremote.test.energy.EnergyOptimisationAssetTest > Test savings calculations took: 11366ms

EnergyOptimisationAssetTest > Test savings calculations FAILED
    Condition not satisfied after 10.00 seconds and 52 attempts
        at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
        at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
        at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations(EnergyOptimisationAssetTest.groovy:324)

        Caused by:
        Condition not satisfied:

        (assetStorageService.find(managerTestSetup.electricityOptimisationAssetId) as EnergyOptimisationAsset).getFinancialSaving().orElse(0d) == -1.5
         |                   |    |                |                                                           |                    |          |
         |                   |    |                3IvOesjjOSunQ9Fb0JGxoo                                      Optional[-3.0]       -3.0       false
         |                   |    <org.openremote.setup.integration.ManagerTestSetup@5560daf0 smartOfficeId=5QGtsMdpXuSY13GVGsU5P9 groundFloorId=57OsUoLq5JFoXFeM6Ct5rp lobbyId=62nnvQjlCH88DESswoCFH8 agentId=4I5tGSSMSpISpwMKsQ9Nyn thingId=6FVWhTcKFf1tdl8eiS7nFc smartBuildingId=6XbK6qOVZWRA8sJXBaWPVD apartment1Id=5B5hxiMNLyh1RQrCL8O6TC apartment1ServiceAgentId=5nh8n7vTu1t3vqPI0ZW9Oe apartment1LivingroomId=3rsAZ4SwFKUEBgtjVtlGb1 apartment1KitchenId=3Qj5AOxkvXq54HJgx983XZ apartment1HallwayId=25jN7n2vN2lVxw1QzgWZss apartment1Bedroom1Id=7jQho9CQuEQSOCC1XZTqTd apartment1BathroomId=3ArrWS0MJdSXrPCJfplIUz apartment2Id=3jm23JN24m6Yk9oviNro3f apartment3Id=7ID5AwQ361fiz71A0I7Fdh apartment2LivingroomId=5YTmK9WLhFhVvTjNEK0UGR apartment2BathroomId=4tw8tYNgDyNDKespOxzAiz apartment3LivingroomId=61lyWcvjr3pVZVeCQG5Kmc realmMasterName=master realmBuildingName=building realmCityName=smartcity realmEnergyName=energy smartCityServiceAgentId=2sxoYTEA6a1Q9GCVakQSCV area1Id=2hc2TrIJVwI54zin7wu4UX microphone1Id=5isrLjiMw2u4BXTCyYiryp peopleCounter1AssetId=76NGjk6Oyj3v0T5b6eyC10 peopleCounter2AssetId=5epDCNfCenobtr8aVakCY5 peopleCounter3AssetId=2yUunxJ1cRCYb86GdWZYaY electricityOptimisationAssetId=3IvOesjjOSunQ9Fb0JGxoo electricityConsumerAssetId=4EmmbLWs9zC8zSJ28znSNL electricitySolarAssetId=5xK5qMsDYvbyZpkirb92cS electricityWindAssetId=5OYyO9S1zYGFWgEvxkZH0r electricitySupplierAssetId=3LN9mhEfElABStV8YA2nig electricityBatteryAssetId=20wpJQkosb1NRT8Fjqkvx8 light1Id=64V8sX0sXLCp7faECIktm5 light2Id=3VpLHSuUYLWsNdsKpBkmcb provisionDocRoot=deployment/manager/provisioning timerService=TimerService{clock=PSEUDO} persistenceService=ManagerPersistenceService{database=POSTGRES, persistenceUnitName='OpenRemotePU'} identityService=ManagerIdentityService{identityProvider=ManagerKeycloakIdentityProvider{}} assetStorageService=AssetStorageService{} assetProcessingService=AssetProcessingService{} assetDatapointService=AssetDatapointService{} assetPredictedDatapointService=AssetPredictedDatapointService{} rulesetStorageService=RulesetStorageService{} setupService=SetupService{} EMPTY_META=[]>
         |                   EnergyOptimisationAsset{id='3IvOesjjOSunQ9Fb0JGxoo', name='Optimisation', type ='EnergyOptimisationAsset', parentId='null', realm='energy'}
         AssetStorageService{}
            at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure13(EnergyOptimisationAssetTest.groovy:325)
            at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure13(EnergyOptimisationAssetTest.groovy)
            at app//groovy.lang.Closure.call(Closure.java:412)
            at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
            ... 2 more
```

**Comment by dominiquekleeven** [comment]
Just adding that this does still ocassionally occur

https://github.com/openremote/openremote/actions/runs/12871313382/job/35884312742#step:38:417

**Comment by ebariaux** [comment]
Confirm it still occurs with head of master

**Comment by dominiquekleeven** [comment]
Failed again today, so still occuring
https://github.com/openremote/openremote/actions/runs/15270406150/job/42944459115#step:34:1133

```
EnergyOptimisationAssetTest > Test storage asset with consumer and producer PASSED
  Test Test savings calculations FAILED (11.1s)

  Condition not satisfied after 10.00 seconds and 50 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:206)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:158)
      at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations(EnergyOptimisationAssetTest.groovy:298)
  Caused by: Condition not satisfied:
  
  setpoints[6].value == -10d
  |        |   |     |
  |        |   0.0   false
  |        ValueDatapoint{timestamp='1748541600000', value=0.0}
  [ValueDatapoint{timestamp='1748476800000', value=10.0}, ValueDatapoint{timestamp='1748487600000', value=10.0}, ValueDatapoint{timestamp='1748498400000', value=10.0}, ValueDatapoint{timestamp='1748509200000', value=-10.0}, ValueDatapoint{timestamp='1748520000000', value=-10.0}, ValueDatapoint{timestamp='1748530800000', value=-10.0}, ValueDatapoint{timestamp='1748541600000', value=0.0}]
      at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure12(EnergyOptimisationAssetTest.groovy:320)
      at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure12(EnergyOptimisationAssetTest.groovy)
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:186)
      ... 2 more

org.openremote.test.energy.EnergyOptimisationAssetTest > Test savings calculations took: 11154ms

EnergyOptimisationAssetTest > Test savings calculations FAILED
    Condition not satisfied after 10.00 seconds and 50 attempts
        at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:206)
        at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:158)
        at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations(EnergyOptimisationAssetTest.groovy:298)

        Caused by:
        Condition not satisfied:

        setpoints[6].value == -10d
        |        |   |     |
        |        |   0.0   false
        |        ValueDatapoint{timestamp='1748541600000', value=0.0}
        [ValueDatapoint{timestamp='1748476800000', value=10.0}, ValueDatapoint{timestamp='1748487600000', value=10.0}, ValueDatapoint{timestamp='1748498400000', value=10.0}, ValueDatapoint{timestamp='1748509200000', value=-10.0}, ValueDatapoint{timestamp='1748520000000', value=-10.0}, ValueDatapoint{timestamp='1748530800000', value=-10.0}, ValueDatapoint{timestamp='1748541600000', value=0.0}]
            at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure12(EnergyOptimisationAssetTest.groovy:320)
            at org.openremote.test.energy.EnergyOptimisationAssetTest.Test savings calculations_closure12(EnergyOptimisationAssetTest.groovy)
            at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:186)
            ... 2 more

org.openremote.test.energy.EnergyOptimisationTest
```
