### ISSUE TITLE
KNXProtocolTest systematically failing on (my) Mac

### ISSUE THREAD

**Issue by ebariaux** [openremote/openremote#1527]
**Describe the bug**
KNXProtocolTest systematically failing on (my) Mac

**To Reproduce**
Run KNXProtocolTest

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.1.1

**Comment by wborn** [comment]
Please add some logging as well.

**Comment by wborn** [comment]
Maybe it cannot use the KNX server because of your network setup or something else is using the UDP port?

See [knx-server-config-mac.xml](https://github.com/openremote/openremote/blob/master/test/src/test/resources/org/openremote/test/protocol/knx/knx-server-config-mac.xml).

**Comment by ebariaux** [comment]
**Logs**

2024-12-10 15:17:57.537  FINE    [ContainerExecutor-17          ] rg.openremote.manager.agent.AgentService : Starting protocol instance: KNX[knx://null]
2024-12-10 15:17:57.543  FINE    [ContainerExecutor-16          ] ote.manager.asset.AssetProcessingService : <<< Attribute event processed in 4ms: processor=ContainerExecutor-16, event=AttributeEvent{timestamp=2024-12-10T14:17:57.549Z, ref=AttributeRef{id='5Cf8EgDDqBzyPcfEVeZG9o', name='agentStatus'}, realm=master, source=AgentService, valueType=org.openremote.model.asset.agent.ConnectionStatus}
2024-12-10 15:17:57.544  INFO    [ContainerExecutor-17          ] netip.KNXnet/IP Tunneling 127.0.0.1:3671 : establish connection from /127.0.0.1:60284 to /127.0.0.1:3671
2024-12-10 15:18:07.552  SEVERE  [ContainerExecutor-17          ] netip.KNXnet/IP Tunneling 127.0.0.1:3671 : establishing connection failed, timeout connecting to control endpoint /127.0.0.1:3671
2024-12-10 15:18:07.552  INFO    [ContainerExecutor-17          ] gent.protocol.knx.KNXConnection.PROTOCOL : Connection error
2024-12-10 15:18:07.552  FINEST  [ContainerExecutor-17          ] gent.protocol.knx.KNXConnection.PROTOCOL : Scheduling reconnection in '2000' milliseconds
2024-12-10 15:18:07.553  FINE    [ContainerExecutor-17          ] rg.openremote.manager.agent.AgentService : Started protocol instance:KNX[knx://KNXConnection{gatewayAddress='127.0.0.1', gatewayPort=3671}]
2024-12-10 15:18:07.559  FINE    [ContainerExecutor-17          ] rg.openremote.manager.agent.AgentService : Starting protocol instance: KNX[knx://null]
2024-12-10 15:18:07.559  FINE    [ContainerExecutor-39          ] ote.manager.asset.AssetProcessingService : <<< Attribute event processed in 6ms: processor=ContainerExecutor-39, event=AttributeEvent{timestamp=2024-12-10T14:18:07.562Z, ref=AttributeRef{id='5Cf8EgDDqBzyPcfEVeZG9o', name='agentStatus'}, realm=master, source=AgentService, valueType=org.openremote.model.asset.agent.ConnectionStatus}
2024-12-10 15:18:07.559  INFO    [ContainerExecutor-17          ] .agent.protocol.knx.KNXProtocol.PROTOCOL : No KNX gateway IP address provided for protocol: KNX[knx://null]
2024-12-10 15:18:07.559  SEVERE  [ContainerExecutor-17          ] rg.openremote.manager.agent.AgentService : Failed to start protocol 'KNX[knx://null]': KNXAgent{id='370TDrxEWZ0dPghKe7uOvM', name='KNX Agent 2', type ='KNXAgent', parentId='null', realm='master'}
java.lang.IllegalArgumentException: No KNX gateway IP address provided for protocol: KNX[knx://null]
	at org.openremote.agent.protocol.knx.KNXProtocol.lambda$doStart$0(KNXProtocol.java:73)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.openremote.agent.protocol.knx.KNXProtocol.doStart(KNXProtocol.java:70)
	at org.openremote.agent.protocol.AbstractProtocol.start(AbstractProtocol.java:82)
	at org.openremote.manager.agent.AgentService.startAgent(AgentService.java:415)
	at org.openremote.manager.agent.AgentService.lambda$doAgentInit$14(AgentService.java:400)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-10 15:18:07.564  FINE    [ContainerExecutor-19          ] ote.manager.asset.AssetProcessingService : <<< Attribute event processed in 4ms: processor=ContainerExecutor-19, event=AttributeEvent{timestamp=2024-12-10T14:18:07.570Z, ref=AttributeRef{id='370TDrxEWZ0dPghKe7uOvM', name='agentStatus'}, realm=master, source=AgentService, valueType=org.openremote.model.asset.agent.ConnectionStatus}
2024-12-10 15:18:07.625  FINEST  [ContainerExecutor-9           ] gent.protocol.knx.KNXConnection.PROTOCOL : Disconnecting
2024-12-10 15:18:07.629  FINE    [ContainerExecutor-9           ] container.persistence.PersistenceService : Rolling back failed transaction
2024-12-10 15:18:07.630  INFO    [Test worker                   ] calimero.server.gateway.knx-server       : knx-server: user request for shutdown
2024-12-10 15:18:07.631  FINE    [ContainerExecutor-12          ] rg.openremote.manager.agent.AgentService : Starting protocol instance: KNX[knx://null]
2024-12-10 15:18:07.631  INFO    [ContainerExecutor-12          ] .agent.protocol.knx.KNXProtocol.PROTOCOL : No KNX gateway IP address provided for protocol: KNX[knx://null]
2024-12-10 15:18:07.631  SEVERE  [ContainerExecutor-12          ] rg.openremote.manager.agent.AgentService : Failed to start protocol 'KNX[knx://null]': KNXAgent{id='370TDrxEWZ0dPghKe7uOvM', name='KNX Agent 2', type ='KNXAgent', parentId='null', realm='master'}
java.lang.IllegalArgumentException: No KNX gateway IP address provided for protocol: KNX[knx://null]
	at org.openremote.agent.protocol.knx.KNXProtocol.lambda$doStart$0(KNXProtocol.java:73)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.openremote.agent.protocol.knx.KNXProtocol.doStart(KNXProtocol.java:70)
	at org.openremote.agent.protocol.AbstractProtocol.start(AbstractProtocol.java:82)
	at org.openremote.manager.agent.AgentService.startAgent(AgentService.java:415)
	at org.openremote.manager.agent.AgentService.lambda$doAgentInit$14(AgentService.java:400)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-12-10 15:18:07.632  FINE    [ContainerExecutor-34          ] container.persistence.PersistenceService : Rolling back failed transaction
2024-12-10 15:18:07.632  INFO    [knx-server control endpo...1.1] calimero.server.knx-server               : knx-server control endpoint 1.1.1 closed
2024-12-10 15:18:07.633  FINE    [ContainerExecutor-10          ] container.persistence.PersistenceService : Rolling back failed transaction
2024-12-10 15:18:07.634  FINE    [ContainerExecutor-9           ] ote.manager.asset.AssetProcessingService : Route 'AttributeEvent-Processor' error processing message: org.openremote.manager.asset.AssetProcessingException: ASSET_NOT_FOUND (5Cf8EgDDqBzyPcfEVeZG9o)
2024-12-10 15:18:07.634  FINE    [ContainerExecutor-34          ] ote.manager.asset.AssetProcessingService : Route 'AttributeEvent-Processor' error processing message: org.openremote.manager.asset.AssetProcessingException: ASSET_NOT_FOUND (5Cf8EgDDqBzyPcfEVeZG9o)
2024-12-10 15:18:07.634  FINE    [ContainerExecutor-10          ] ote.manager.asset.AssetProcessingService : Route 'AttributeEvent-Processor' error processing message: org.openremote.manager.asset.AssetProcessingException: ASSET_NOT_FOUND (370TDrxEWZ0dPghKe7uOvM)

Condition not satisfied after 10,05 seconds and 2 attempts
Condition not satisfied after 10,05 seconds and 2 attempts
	at spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
	at spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
	at org.openremote.test.protocol.KNXProtocolTest.Check KNX protocol(KNXProtocolTest.groovy:105)
Caused by: Condition not satisfied:

agentService.getAgent(knxAgent1.id).getAgentStatus().orElse(null) == ConnectionStatus.CONNECTED
|            |        |         |   |                |            |  |
|            |        |         |   |                WAITING      |  class org.openremote.model.asset.agent.ConnectionStatus
|            |        |         |   Optional[WAITING]             false
|            |        |         5Cf8EgDDqBzyPcfEVeZG9o
|            |        KNXAgent{id='5Cf8EgDDqBzyPcfEVeZG9o', name='KNX Agent 1', type ='KNXAgent', parentId='null', realm='master'}
|            KNXAgent{id='5Cf8EgDDqBzyPcfEVeZG9o', name='KNX Agent 1', type ='KNXAgent', parentId='null', realm='master'}
AgentService{}

	at org.openremote.test.protocol.KNXProtocolTest.Check KNX protocol_closure2(KNXProtocolTest.groovy:108)
	at org.openremote.test.protocol.KNXProtocolTest.Check KNX protocol_closure2(KNXProtocolTest.groovy)
	at groovy.lang.Closure.call(Closure.java:412)
	at spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
	... 2 more


Condition not satisfied:

agentService.getAgent(knxAgent1.id).getAgentStatus().orElse(null) == ConnectionStatus.CONNECTED
|            |        |         |   |                |            |  |
|            |        |         |   |                WAITING      |  class org.openremote.model.asset.agent.ConnectionStatus
|            |        |         |   Optional[WAITING]             false
|            |        |         5Cf8EgDDqBzyPcfEVeZG9o
|            |        KNXAgent{id='5Cf8EgDDqBzyPcfEVeZG9o', name='KNX Agent 1', type ='KNXAgent', parentId='null', realm='master'}
|            KNXAgent{id='5Cf8EgDDqBzyPcfEVeZG9o', name='KNX Agent 1', type ='KNXAgent', parentId='null', realm='master'}
AgentService{}

Condition not satisfied:

agentService.getAgent(knxAgent1.id).getAgentStatus().orElse(null) == ConnectionStatus.CONNECTED
|            |        |         |   |                |            |  |
|            |        |         |   |                WAITING      |  class org.openremote.model.asset.agent.ConnectionStatus
|            |        |         |   Optional[WAITING]             false
|            |        |         5Cf8EgDDqBzyPcfEVeZG9o
|            |        KNXAgent{id='5Cf8EgDDqBzyPcfEVeZG9o', name='KNX Agent 1', type ='KNXAgent', parentId='null', realm='master'}
|            KNXAgent{id='5Cf8EgDDqBzyPcfEVeZG9o', name='KNX Agent 1', type ='KNXAgent', parentId='null', realm='master'}
AgentService{}

	at org.openremote.test.protocol.KNXProtocolTest.Check KNX protocol_closure2(KNXProtocolTest.groovy:108)
	at org.openremote.test.protocol.KNXProtocolTest.Check KNX protocol_closure2(KNXProtocolTest.groovy)
	at app//groovy.lang.Closure.call(Closure.java:412)
	at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
	at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
	at org.openremote.test.protocol.KNXProtocolTest.Check KNX protocol(KNXProtocolTest.groovy:105)

**Comment by ebariaux** [comment]
This is systematic, the test never succeeds, still with current master head as of today.

**Comment by aktur** [comment]
How can that you have 15.5.1? Mine is 15.4.1, and I just updated it today.

**Comment by aktur** [comment]
Oh, sorry, must be blind, you have 15.1.1 :-)
