### ISSUE TITLE
MQTTClientProtocolTest unstable

### ISSUE THREAD

**Issue by wborn** [openremote/openremote#1528]
It failed in this build: https://github.com/openremote/openremote/actions/runs/12233465688/job/34120616956

```
org.openremote.test.protocol.mqtt.MQTTClientProtocolTest > Check MQTT client protocol mTLS support took: 103371ms

MQTTClientProtocolTest > Check MQTT client protocol mTLS support FAILED
    Condition not satisfied after 100.00 seconds and 498 attempts
        at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
        at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
        at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol mTLS support(MQTTClientProtocolTest.groovy:270)

        Caused by:
        Condition not satisfied:

        agent.getAgentStatus().orElse(null) == ConnectionStatus.CONNECTED
        |     |                |            |  |
        |     |                WAITING      |  class org.openremote.model.asset.agent.ConnectionStatus
        |     Optional[WAITING]             false
        MQTTAgent{id='2qm1DMdvAQgxR20YJU142q', name='Test agent', type ='MQTTAgent', parentId='null', realm='master'}
            at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol mTLS support_closure7(MQTTClientProtocolTest.groovy:272)
            at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol mTLS support_closure7(MQTTClientProtocolTest.groovy)
            at app//groovy.lang.Closure.call(Closure.java:412)
            at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
            ... 2 more
```

**Comment by pankalog** [comment]
@wborn @richturner the test uses `test.mosquitto.org:8884`, which uses mTLS for authentication. We cannot perform the test locally, as the broker does not support mTLS authentication. If you want to, I can exclude the test.

Otherwise, I can create a crude implementation by creating a new Artemis acceptor with predefined keystores that contain the correct certificates. It'd only be available when running in a test configuration. Maybe integrate it somehow with `KeystoreService`.

**Comment by wborn** [comment]
Still unstable, see:

https://github.com/openremote/openremote/actions/runs/19431804119/job/55597675156?pr=2256

```
org.openremote.test.protocol.mqtt.MQTTClientProtocolTest > Check MQTT client protocol wildcard subscriptions took: 20290ms
  Test Check MQTT client protocol wildcard subscriptions FAILED (20.2s)

  Condition not satisfied after 20.00 seconds and 101 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:206)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:158)
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol wildcard subscriptions(MQTTClientProtocolTest.groovy:632)
  Caused by: Condition not satisfied:
  
  defaultMQTTHandler.sessionSubscriptionConsumers.get(getConnectionIDString(connection)).size() == 3
  |                  |                            |   |                     |            |      |
  |                  |                            |   |                     |            1      false
  |                  |                            |   |                     <org.apache.activemq.artemis.core.protocol.mqtt.MQTTConnection@325004b9 destroyed=false connected=true receiveMaximum=-1 protocolVersion=null clientIdAssignedByBroker=false failureListeners=[org.apache.activemq.artemis.core.protocol.mqtt.MQTTFailureListener@2706d645, org.openremote.manager.mqtt.MQTTBrokerService$3@286f05c2, ServerSessionImpl(), ServerSessionImpl()] closeListeners=[] transportConnection=org.apache.activemq.artemis.core.remoting.impl.netty.NettyServerConnection@5d80b76d[ID=7343fcc4, local= /127.0.0.1:1883, remote=/127.0.0.1:45726] executor=null creationTime=1763391092111 destroyed=false dataReceived=false clientId=6DwkP3cKPSEdUALGXCrcR2 subject=Subject:
  |                  |                            |   |                     	Principal: service-account-serviceuser
  |                  |                            |   |                     	Principal: write:assets
  |                  |                            |   |                     	Principal: write:services
  |                  |                            |   |                     	Principal: read:assets
  |                  |                            |   |                     	Principal: write:attributes
  |                  |                            |   |                     	Principal: read:services
  |                  |                            |   |                     	Principal: service-account-serviceuser
  |                  |                            |   |                     	Principal: org.openremote.manager.security.RemotingConnectionPrincipal@3e4c252
  |                  |                            |   |                     	Private Credential: ***
  |                  |                            |   |                     >
  |                  |                            |   7ced8dfffecae220-00001d1a-00000050-7f3a2083ef4cb58d-7343fcc4
  |                  |                            [building/6DwkP3cKPSEdUALGXCrcR2/attributevalue/test/3e5P4ERLVpmwywGfFSSvOh:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@5bd514d4]
  |                  [7ced8dfffecae220-00001d1a-00000052-2c0c98b86f4cc0d4-f3a04dce:[building/3s441EpJzUEd3KU7CbMjXc/attributevalue/+/3S60mAReJoJATYO9rG7uLJ:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@21663895, building/3s441EpJzUEd3KU7CbMjXc/attributevalue/uvIndex/7CMDCSr1Mj47NwF0mm5kWj:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@55f4aa9b, building/3s441EpJzUEd3KU7CbMjXc/attributevalue/+/63MHtKzsNZFdYREbUsWKpv:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@4ef74007], 7ced8dfffecae220-00001d1a-0000004e-e0da023cef4cb239-c52ee095:[building/5cjQtw48qovfXYnXcOhV4l/attributevalue/targetTemperature/3rsAZ4SwFKUEBgtjVtlGb1:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@4be73fad], 7ced8dfffecae220-00001d1a-00000050-7f3a2083ef4cb58d-7343fcc4:[building/6DwkP3cKPSEdUALGXCrcR2/attributevalue/test/3e5P4ERLVpmwywGfFSSvOh:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@5bd514d4]]
  <org.openremote.manager.mqtt.DefaultMQTTHandler@6edeb8ca sessionSubscriptionConsumers=[7ced8dfffecae220-00001d1a-00000052-2c0c98b86f4cc0d4-f3a04dce:[building/3s441EpJzUEd3KU7CbMjXc/attributevalue/+/3S60mAReJoJATYO9rG7uLJ:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@21663895, building/3s441EpJzUEd3KU7CbMjXc/attributevalue/uvIndex/7CMDCSr1Mj47NwF0mm5kWj:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@55f4aa9b, building/3s441EpJzUEd3KU7CbMjXc/attributevalue/+/63MHtKzsNZFdYREbUsWKpv:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@4ef74007], 7ced8dfffecae220-00001d1a-0000004e-e0da023cef4cb239-c52ee095:[building/5cjQtw48qovfXYnXcOhV4l/attributevalue/targetTemperature/3rsAZ4SwFKUEBgtjVtlGb1:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@4be73fad], 7ced8dfffecae220-00001d1a-00000050-7f3a2083ef4cb58d-7343fcc4:[building/6DwkP3cKPSEdUALGXCrcR2/attributevalue/test/3e5P4ERLVpmwywGfFSSvOh:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f1ae9a76eb0@5bd514d4]] authorizationCache=com.google.common.cache.LocalCache$LocalManualCache@2b05cd47 eventSubscriptionCache=com.google.common.cache.LocalCache$LocalManualCache@5f864758 clientEventService=ClientEventService{} mqttBrokerService=Routes: [Route(Persistence-UserAndAssetLink)[From[seda://PersistenceTopic?multipleConsumers=true&concurrentConsumers=1&waitForTaskToComplete=NEVER&purgeWhenStopping=true&discardIfNoConsumers=true&size=25000] -> [Filter[{body instanceof org.openremote.model.PersistenceEvent} -> [process[Processor@0x18d8af69]]]]]] messageBrokerService=MessageBrokerService{} identityProvider=ManagerKeycloakIdentityProvider{} executorService=java.util.concurrent.ThreadPoolExecutor@79377ef6[Running, pool size = 40, active threads = 0, queued tasks = 0, completed tasks = 7688] timerService=TimerService{clock=PSEUDO} isKeycloak=true clientSession=ClientSessionImpl [name=d806192f-c3c4-11f0-8178-d68fe665c9ce, username=null, closed=false, factory = org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl@745ce46a, metaData=(jms-session=Internal session,)]@674fe833 producer=org.apache.activemq.artemis.core.client.impl.ClientProducerImpl@74233f04>
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol wildcard subscriptions_closure32(MQTTClientProtocolTest.groovy:648)
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol wildcard subscriptions_closure32(MQTTClientProtocolTest.groovy)
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:186)
      ... 2 more
```

---

https://github.com/openremote/openremote/actions/runs/19366115803/job/55409554273?pr=2247

```
  Test Check MQTT client protocol wildcard subscriptions FAILED (20.2s)

  Condition not satisfied after 20.00 seconds and 101 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:206)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:158)
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol wildcard subscriptions(MQTTClientProtocolTest.groovy:632)
  Caused by: Condition not satisfied:
  
  defaultMQTTHandler.sessionSubscriptionConsumers.get(getConnectionIDString(connection)).size() == 3
  |                  |                            |   |                     |            |      |
  |                  |                            |   |                     |            1      false
  |                  |                            |   |                     <org.apache.activemq.artemis.core.protocol.mqtt.MQTTConnection@4963aba0 destroyed=false connected=true receiveMaximum=-1 protocolVersion=null clientIdAssignedByBroker=false failureListeners=[org.apache.activemq.artemis.core.protocol.mqtt.MQTTFailureListener@da9e449, org.openremote.manager.mqtt.MQTTBrokerService$3@659b9707, ServerSessionImpl(), ServerSessionImpl()] closeListeners=[] transportConnection=org.apache.activemq.artemis.core.remoting.impl.netty.NettyServerConnection@507e6fdd[ID=cc6074a0, local= /127.0.0.1:1883, remote=/127.0.0.1:47220] executor=null creationTime=1763127852954 destroyed=false dataReceived=false clientId=2PVou7d3FgwO0Xr402VJNl subject=Subject:
  |                  |                            |   |                     	Principal: service-account-serviceuser
  |                  |                            |   |                     	Principal: write:assets
  |                  |                            |   |                     	Principal: write:services
  |                  |                            |   |                     	Principal: read:assets
  |                  |                            |   |                     	Principal: write:attributes
  |                  |                            |   |                     	Principal: read:services
  |                  |                            |   |                     	Principal: service-account-serviceuser
  |                  |                            |   |                     	Principal: org.openremote.manager.security.RemotingConnectionPrincipal@4ebe047a
  |                  |                            |   |                     	Private Credential: ***
  |                  |                            |   |                     >
  |                  |                            |   7c1e52fffeb65df1-00001cd4-00000054-0ea154e27f9bff99-cc6074a0
  |                  |                            [building/2PVou7d3FgwO0Xr402VJNl/attributevalue/test/7acQb1o1QSJ4ZuiEehgzcF:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@765eccf9]
  |                  [7c1e52fffeb65df1-00001cd4-00000052-66fdcdadff9bfc4b-8780d262:[building/2QHzBIaY9094ltBj8tOcTR/attributevalue/targetTemperature/3rsAZ4SwFKUEBgtjVtlGb1:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@3a93b66d], 7c1e52fffeb65df1-00001cd4-00000054-0ea154e27f9bff99-cc6074a0:[building/2PVou7d3FgwO0Xr402VJNl/attributevalue/test/7acQb1o1QSJ4ZuiEehgzcF:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@765eccf9], 7c1e52fffeb65df1-00001cd4-00000056-6e76ca097f9c0ad1-0102d160:[building/4EskwaMl1Sow8efMSp2LVi/attributevalue/+/70NYOWAmSDS3X8Y5agOCQp:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@4fa3974c, building/4EskwaMl1Sow8efMSp2LVi/attributevalue/uvIndex/5UPGtk30DH6TEtlAGgirmT:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@9ba7a64, building/4EskwaMl1Sow8efMSp2LVi/attributevalue/+/35KkviDNmzXTjonjWq4siG:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@2ebd95e0]]
  <org.openremote.manager.mqtt.DefaultMQTTHandler@420f696f sessionSubscriptionConsumers=[7c1e52fffeb65df1-00001cd4-00000052-66fdcdadff9bfc4b-8780d262:[building/2QHzBIaY9094ltBj8tOcTR/attributevalue/targetTemperature/3rsAZ4SwFKUEBgtjVtlGb1:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@3a93b66d], 7c1e52fffeb65df1-00001cd4-00000054-0ea154e27f9bff99-cc6074a0:[building/2PVou7d3FgwO0Xr402VJNl/attributevalue/test/7acQb1o1QSJ4ZuiEehgzcF:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@765eccf9], 7c1e52fffeb65df1-00001cd4-00000056-6e76ca097f9c0ad1-0102d160:[building/4EskwaMl1Sow8efMSp2LVi/attributevalue/+/70NYOWAmSDS3X8Y5agOCQp:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@4fa3974c, building/4EskwaMl1Sow8efMSp2LVi/attributevalue/uvIndex/5UPGtk30DH6TEtlAGgirmT:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@9ba7a64, building/4EskwaMl1Sow8efMSp2LVi/attributevalue/+/35KkviDNmzXTjonjWq4siG:org.openremote.manager.mqtt.DefaultMQTTHandler$$Lambda/0x00007f722daccc88@2ebd95e0]] authorizationCache=com.google.common.cache.LocalCache$LocalManualCache@2e04bdca eventSubscriptionCache=com.google.common.cache.LocalCache$LocalManualCache@7dce56b1 clientEventService=ClientEventService{} mqttBrokerService=Routes: [Route(Persistence-UserAndAssetLink)[From[seda://PersistenceTopic?multipleConsumers=true&concurrentConsumers=1&waitForTaskToComplete=NEVER&purgeWhenStopping=true&discardIfNoConsumers=true&size=25000] -> [Filter[{body instanceof org.openremote.model.PersistenceEvent} -> [process[Processor@0x61999aab]]]]]] messageBrokerService=MessageBrokerService{} identityProvider=ManagerKeycloakIdentityProvider{} executorService=java.util.concurrent.ThreadPoolExecutor@3229b923[Running, pool size = 40, active threads = 0, queued tasks = 0, completed tasks = 7946] timerService=TimerService{clock=PSEUDO} isKeycloak=true clientSession=ClientSessionImpl [name=f141cab7-c15f-11f0-95e9-6a5b2fcf27bd, username=null, closed=false, factory = org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl@437049f5, metaData=(jms-session=Internal session,)]@47dc13a6 producer=org.apache.activemq.artemis.core.client.impl.ClientProducerImpl@622c549>
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol wildcard subscriptions_closure32(MQTTClientProtocolTest.groovy:648)
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client protocol wildcard subscriptions_closure32(MQTTClientProtocolTest.groovy)
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:186)
      ... 2 more

```

**Comment by pankalog** [comment]
@wborn the errors are unrelated to this issue, the mTLS support test was unstable due to the unavailability of the [mosquitto MQTT test broker](https://test.mosquitto.org/), so it was ignored. This one is related to the wildcard subscription support test. I'd say that if we do want to create a new issue, then we should open a new one.

**Comment by richturner** [comment]
The fix here shoul resolve this issue https://github.com/openremote/openremote/pull/2265

**Comment by Ekhorn** [comment]
Failed once again https://github.com/openremote/openremote/actions/runs/33856585958/job/100971261827

```
org.openremote.test.protocol.mqtt.MQTTClientProtocolTest

  Test Check MQTT client FAILED (20.5s)

  Condition not satisfied after 20.00 seconds and 200 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:205)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:157)
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client(MQTTClientProtocolTest.groovy:214)
  Caused by: Condition not satisfied:
  
  defaultMQTTHandler.sessionSubscriptionConsumers.get(getConnectionIDString(connection)).size() == 5
  |                  |                            |   |                     |            |      |
  |                  [:]                          [:] |                     |            4      false
  |                                                   |                     <org.apache.activemq.artemis.core.protocol.mqtt.MQTTConnection@178a30bc destroyed=inaccessible connected=inaccessible receiveMaximum=inaccessible protocolVersion=inaccessible clientIdAssignedByBroker=inaccessible failureListeners=inaccessible closeListeners=inaccessible transportConnection=inaccessible executor=inaccessible creationTime=inaccessible destroyed=inaccessible dataReceived=inaccessible clientId=inaccessible subject=inaccessible>
  |                                                   70a8a5fffe1951ae-000019f2-00000075-23d895ff28b6bc9a-e8cea4a0
  <org.openremote.manager.mqtt.DefaultMQTTHandler@890d5ef sessionSubscriptionConsumers=inaccessible authorizationCache=inaccessible eventSubscriptionCache=inaccessible clientEventService=inaccessible mqttBrokerService=inaccessible messageBrokerService=inaccessible identityProvider=inaccessible executorService=inaccessible timerService=inaccessible isKeycloak=inaccessible clientSession=inaccessible producer=inaccessible>
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client_closure9(MQTTClientProtocolTest.groovy:220)
      at org.openremote.test.protocol.mqtt.MQTTClientProtocolTest.Check MQTT client_closure9(MQTTClientProtocolTest.groovy)
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
      ... 2 more
```

**Comment by pankalog** [comment]
@richturner @ebariaux I think we can temporarily disable this test. The mTLS PRs (marked as ready to review some minutes ago) delete these tests and actually test the mTLS functionality within the OpenRemote broker itself.

Let me know if I should make a PR for disabling that test or if someone else can sneak that change in and link this issue in the commit.
