### ISSUE TITLE
AssetDatapointTest unstable

### ISSUE THREAD

**Issue by wborn** [openremote/openremote#1536]
Today I've seen it fail in 2 PR builds:

* https://github.com/openremote/openremote/actions/runs/12260552963/attempts/1
* https://github.com/openremote/openremote/actions/runs/12260732781/attempts/1

```
org.openremote.test.assets.AssetDatapointTest

  Test Test number and toggle attribute storage, retrieval and purging FAILED (11.9s)

  Condition not satisfied after 10.00 seconds and 50 attempts
      at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
      at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
      at org.openremote.test.assets.AssetDatapointTest.Test number and toggle attribute storage, retrieval and purging(AssetDatapointTest.groovy:146)
  Caused by: java.lang.IllegalStateException: Could not query data points for 56B0bZFzuZ7usgN0RbxPi0. It exceeds the data limit.
      at org.openremote.manager.datapoint.AbstractDatapointService.canQueryDatapoints(AbstractDatapointService.java:230)
      at org.openremote.manager.datapoint.AbstractDatapointService.queryDatapoints(AbstractDatapointService.java:205)
      at org.openremote.manager.datapoint.AbstractDatapointService.queryDatapoints(AbstractDatapointService.java:186)
      at org.openremote.test.assets.AssetDatapointTest.Test number and toggle attribute storage, retrieval and purging_closure8(AssetDatapointTest.groovy:154)
      at org.openremote.test.assets.AssetDatapointTest.Test number and toggle attribute storage, retrieval and purging_closure8(AssetDatapointTest.groovy)
      at groovy.lang.Closure.call(Closure.java:412)
      at spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
      ... 2 more

org.openremote.test.assets.AssetDatapointTest > Test number and toggle attribute storage, retrieval and purging took: 11942ms

AssetDatapointTest > Test number and toggle attribute storage, retrieval and purging FAILED
    Condition not satisfied after 10.00 seconds and 50 attempts
        at app//spock.util.concurrent.PollingConditions.within(PollingConditions.java:185)
        at app//spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:140)
        at org.openremote.test.assets.AssetDatapointTest.Test number and toggle attribute storage, retrieval and purging(AssetDatapointTest.groovy:146)

        Caused by:
        java.lang.IllegalStateException: Could not query data points for 56B0bZFzuZ7usgN0RbxPi0. It exceeds the data limit.
            at org.openremote.manager.datapoint.AbstractDatapointService.canQueryDatapoints(AbstractDatapointService.java:230)
            at org.openremote.manager.datapoint.AbstractDatapointService.queryDatapoints(AbstractDatapointService.java:205)
            at org.openremote.manager.datapoint.AbstractDatapointService.queryDatapoints(AbstractDatapointService.java:186)
            at org.openremote.test.assets.AssetDatapointTest.Test number and toggle attribute storage, retrieval and purging_closure8(AssetDatapointTest.groovy:154)
            at org.openremote.test.assets.AssetDatapointTest.Test number and toggle attribute storage, retrieval and purging_closure8(AssetDatapointTest.groovy)
            at groovy.lang.Closure.call(Closure.java:412)
            at spock.util.concurrent.PollingConditions.within(PollingConditions.java:168)
            ... 2 more
```

**Comment by dominiquekleeven** [comment]
https://github.com/openremote/openremote/actions/runs/12868570574/job/35875505465#step:38:276

Just adding that this test in particular is still causing issues
