### ISSUE TITLE
Race condition in MQTT Authorization check

### ISSUE THREAD

**Issue by Raqbit** [openremote/openremote#257]
## Issue
When connecting to the built-in MQTT broker with `mosquitto_sub` I was getting denied access (silently, without getting an error in the MQTT client) while the service account I was using did actually have the `read:assets` permission required to subscribe to an asset topic. After looking in the OpenRemote logs it appeared something was not registering my connection properly before `verifyRights` was checking if the client in question has the correct rights to subscribe to the given topic.

**OpenRemote logs**:
```
2020-09-22 18:51:34.881  INFO    [nioEventLoopGroup-3-3         ] .manager.mqtt.KeycloakAuthorizatorPolicy : No connection found for clientId: smartcity_test
2020-09-22 18:51:34.881  WARNING [nioEventLoopGroup-3-3         ] io.moquette.broker.Authorizator          : Client does not have read permissions on the topic CId=smartcity_test, username: mqtt-e0a7f3ba-64a9-4d29-8059-0f3dad6a8527, messageId: 1, topic: assets/54LS0LDCxIqVHnOCAVTK58
``` 

https://github.com/openremote/openremote/blob/f6d5b33d94a3a23352308552f9ca0a8ac88208a8/manager/src/main/java/org/openremote/manager/mqtt/KeycloakAuthorizatorPolicy.java#L61-L65

## Cause
`KeycloakAuthorizatorPolicy#canRead` is called in parallel to `EventInterceptHandler#onConnect`, which causes the `mqttConnectionMap` to be empty when verifying the rights (in `verifyRights`, called by `canRead`), because `EventInterceptHandler#onConnect` (which is expected to run first) hasn't added the connection to the `mqttConnectionMap` yet (it needs to reach out to Keycloak for an access token first).

By adding a `Thread#sleep` hack to `KeycloakAuthorizatorPolicy#canRead`, I was able to get the authorization check to work correctly (mostly as a test for checking that this is actually a race). 

Looking at the MQTT packets in Wireshark it appears that Moquette sends a "Connect Ack" packet despite `onConnect` not being done yet, which allows the client to send a "Subscribe" packet as a response (which then invokes `canRead` while `onConnect` has not finished yet). The Moquette code [confirms this onConnect interceptor is async](https://github.com/moquette-io/moquette/blob/1141e9f7a13f816cb46e57e47999a2de3d7ae1c8/broker/src/main/java/io/moquette/interception/BrokerInterceptor.java#L100), and tracing it back it is called after the "Connect Ack" packet is sent ([link](https://github.com/moquette-io/moquette/blob/6ee013747f6bddf4ecf3050e6349b611cfcbbd93/broker/src/main/java/io/moquette/broker/MQTTConnection.java#L176)).

## Reproduction steps

1. Start OpenRemote (In my case without HAproxy)
1. Open the `smartcity` realm in the Keycloak Admin Console
1. Create a Client in Keycloak
    * Client ID: `mqtt-<random_uuid>`
    * Access type: `confidential`
    * Standard flow: `disabled`
    * Direct Access Grants: `disabled`
    * Service Accounts: `enabled`
1. Add service account roles (using the new "Service Account Roles" tab)
    * Select `openremote` in the client roles dropdown
    * Select `read:assets` and hit `Add selected`
1. Grab the client secret from the "Credentials" tab
1. Connect to the MQTT broker using mosquitto_sub (Should be the same for other clients, as far as I can tell)
   ```sh
   mosquitto_sub -h localhost -p 1883 -t 'assets/<some asset>' -i 'smartcity_<some_identifier>' -u 'mqtt-<random_uuid>' -P '<client_secret>'
   ```
1. It looks like `mosquitto_sub`  hangs, but Moquette acknowledged the connect & subscribe, OpenRemote is just not sending any events as the permission check failed.
1. The errors above should be logged to the OpenRemote log

## Enhanced logs

To showcase the race condition I added some custom log lines noting when `EventInterceptHandler#onConnect` and `KeycloakAuthorizatorPolicy#verifyRights` are invoked and also a line where `onConnect` adds the connection to the `mqttConnectionMap`.

```
2020-09-22 18:51:34.880  INFO    [pool-9-thread-1               ] emote.manager.mqtt.EventInterceptHandler : onConnect in EventInterceptHandler (EventInterceptHandler.java#L92)
2020-09-22 18:51:34.881  INFO    [nioEventLoopGroup-3-3         ] oquette.broker.metrics.MQTTMessageLogger : C->B SUBSCRIBE <smartcity_test> to topics [MqttTopicSubscription[topicFilter=assets/54LS0LDCxIqVHnOCAVTK58, qualityOfService=AT_MOST_ONCE]]
2020-09-22 18:51:34.881  INFO    [nioEventLoopGroup-3-3         ] .manager.mqtt.KeycloakAuthorizatorPolicy : verifyRights in KeycloakAuthorizatorPolicy (KeycloakAuthorizatorPolicy.java#L61)
2020-09-22 18:51:34.881  INFO    [nioEventLoopGroup-3-3         ] .manager.mqtt.KeycloakAuthorizatorPolicy : No connection found for clientId: smartcity_test
2020-09-22 18:51:34.881  WARNING [nioEventLoopGroup-3-3         ] io.moquette.broker.Authorizator          : Client does not have read permissions on the topic CId=smartcity_test, username: mqtt-e0a7f3ba-64a9-4d29-8059-0f3dad6a8527, messageId: 1, topic: assets/54LS0LDCxIqVHnOCAVTK58
2020-09-22 18:51:34.881  INFO    [nioEventLoopGroup-3-3         ] oquette.broker.metrics.MQTTMessageLogger : C<-B SUBACK <smartcity_test> packetID <1>, grantedQoses [128]
2020-09-22 18:51:34.889  INFO    [pool-9-thread-1               ] emote.manager.mqtt.EventInterceptHandler : adding connection to mqttConnectionMap (EventInterceptHandler.java#L97)
```

**Comment by richturner** [comment]
Thanks for this detailed info @Miggets7 can you take a look when you get some time.

**Comment by Miggets7** [comment]
The commit closed this issue a bit too soon.

@Raqbit could you verify the fix? I'll close the issue once you confirm it.

**Comment by Raqbit** [comment]
While the original issue is gone, `accessToken` is used in `EventInterceptHandler#prepareHeaders` (which is called in `onConnect`), which causes the following error to occur:

```
2020-09-23 17:06:02.750  WARNING [pool-9-thread-45              ] emote.manager.mqtt.EventInterceptHandler : Token not set
org.keycloak.common.VerificationException: Token not set
	at org.keycloak.TokenVerifier.parse(TokenVerifier.java:389)
	at org.keycloak.TokenVerifier.getHeader(TokenVerifier.java:416)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.createVerifier(AdapterTokenVerifier.java:110)
	at org.keycloak.adapters.rotation.AdapterTokenVerifier.verifyToken(AdapterTokenVerifier.java:47)
	at org.openremote.manager.mqtt.EventInterceptHandler.prepareHeaders(EventInterceptHandler.java:241)
	at org.openremote.manager.mqtt.EventInterceptHandler.onConnect(EventInterceptHandler.java:95)
	at io.moquette.interception.BrokerInterceptor.lambda$notifyClientConnected$0(BrokerInterceptor.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Miggets7** [comment]
@Raqbit could you verify once more? I guess I was a bit too quick with the previous commit.

**Comment by Raqbit** [comment]
Yup, that error is gone now.

**Comment by Miggets7** [comment]
Great!
