### ISSUE TITLE
'Add user' broken

### ISSUE THREAD

**Issue by pierrekil** [openremote/openremote#457]
@vlichtenberg , Is that fixed in your latest commit?

![Screenshot 2021-07-16 at 13 06 32](https://user-images.githubusercontent.com/11444149/125938703-1c4405fc-a433-445d-84b7-8fb23f84501f.png)

**Comment by dpaardenkooper** [comment]
I have the same issue. I cannot add new users, nor new realms. It is like the UI isn't responding

**Comment by dpaardenkooper** [comment]
Update after digging into the containers <docker logs>

proxy:
<no errors>

manager:
2021-07-18 21:08:39.729  INFO    [WebService task-5             ] security.ManagerKeycloakIdentityProvider : Failed to get tenant for realm: <realmname>
org.jboss.resteasy.client.exception.ResteasyNotFoundException: HTTP 404 Not Found

2021-07-18 21:06:22.498  INFO    [WebService task-5             ] security.ManagerKeycloakIdentityProvider : Failed to create tenant: Tenant{id='null', realm='test', displayName='test', enabled=true, notBefore=null}
org.jboss.resteasy.client.exception.ResteasyClientErrorException: HTTP 409 Conflict

2021-07-18 20:38:32.448  INFO    [WebService task-6             ] security.ManagerKeycloakIdentityProvider : Failed to create tenant: Tenant{id='null', realm='demo', displayName='demo', enabled=true, notBefore=null}
org.jboss.resteasy.client.exception.ResteasyClientErrorException: HTTP 409 Conflict
	at org.jboss.resteasy.client.exception.WebApplicationExceptionWrapper.wrap(WebApplicationExceptionWrapper.java:101)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.handleErrorStatus(ClientInvocation.java:246)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.DefaultEntityExtractorFactory$3.extractEntity(DefaultEntityExtractorFactory.java:50)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy120.create(Unknown Source)
	at org.openremote.manager.security.ManagerKeycloakIdentityProvider.lambda$createTenant$46(ManagerKeycloakIdentityProvider.java:743)
	at org.openremote.container.security.keycloak.KeycloakIdentityProvider.getRealms(KeycloakIdentityProvider.java:252)
	at org.openremote.manager.security.ManagerKeycloakIdentityProvider.createTenant(ManagerKeycloakIdentityProvider.java:739)
	at org.openremote.manager.security.TenantResourceImpl.create(TenantResourceImpl.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

keycloack
20:38:32,537 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-2) ERROR: duplicate key value violates unique constraint "uk_orvsdmla56612eaefiq6wl5oi"
  Detail: Key (name)=(demo) already exists.
20:38:32,539 ERROR [org.keycloak.services.resources.admin.RealmsAdminResource] (default task-2) Conflict detected: org.keycloak.models.ModelDuplicateException: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.keycloak.keycloak-model-jpa@13.0.1//org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:80)
	at org.keycloak.keycloak-model-jpa@13.0.1//org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:62)
	at javax.persistence.api@2.2.3//com.sun.proxy.$Proxy93.flush(Unknown Source)

postgress
ERROR:  duplicate key value violates unique constraint "uk_orvsdmla56612eaefiq6wl5oi"
DETAIL:  Key (name)=(test) already exists.
ERROR:  relation "public.databasechangelog" does not exist at character 22
STATEMENT:  select count(*) from public.databasechangelog
ERROR:  relation "public.databasechangeloglock" does not exist at character 22
STATEMENT:  select count(*) from public.databasechangeloglock
ERROR:  relation "public.databasechangelog" does not exist at character 22
STATEMENT:  select count(*) from public.databasechangelog
ERROR:  duplicate key value violates unique constraint "uk_orvsdmla56612eaefiq6wl5oi"
DETAIL:  Key (name)=(demo) already exists.

**Comment by richturner** [comment]
There was a bad commit to the user UI code which I have now reverted until the dev responsible can fix.

Please try the latest manager image (dated after this comment).

**Comment by dpaardenkooper** [comment]
Thnx. Account creation works!
