### ISSUE TITLE
New java.util.ConcurrentModificationException after recent build.

### ISSUE THREAD

**Issue by aktur** [openremote/openremote#66]
2017-12-20 15:31:23.081  SEVERE  [Messaging-AssetQueue-17       ] org.slf4j.Logger                         : Failed delivery for (MessageId: ID-12bc167b0cea-42311-1513777819300-0-34375 on ExchangeId: ID-12bc167b0cea-42311-1513777819300-0-34376). Exhausted after delivery attempt: 1 caught: java.util.ConcurrentModificationException

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[AssetUpdates      ] [AssetUpdates      ] [seda://AssetQueue?discardIfNoConsumers=false&purgeWhenStopping=true&size=25000] [        29]
[AssetUpdates      ] [filter7           ] [filter[{simple{Simple: ${body}} instanceof org.openremote.model.attribute.Attr] [        29]
[AssetUpdates      ] [doTry1            ] [doTry                                                                         ] [        28]
[AssetUpdates      ] [process12         ] [Processor@0x31dc3f68                                                          ] [         1]
[AssetUpdates      ] [process13         ] [Processor@0x1f904d15                                                          ] [         0]
[AssetUpdates      ] [choice4           ] [when[{header{header(org.openremote.model.attribute.AttributeEvent.SOURCE)} == ] [         0]
[AssetUpdates      ] [process16         ] [Processor@0x4195a66f                                                          ] [         0]
[AssetUpdates      ] [process17         ] [Processor@0x5cf0b3ad                                                          ] [        26]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at java.util.AbstractMap.hashCode(AbstractMap.java:530)
	at org.openremote.model.value.impl.ObjectValueImpl.hashCode(ObjectValueImpl.java:178)
	at java.util.Objects.hashCode(Objects.java:98)
	at java.util.HashMap$Node.hashCode(HashMap.java:297)
	at java.util.AbstractMap.hashCode(AbstractMap.java:530)
	at org.openremote.model.value.impl.ObjectValueImpl.hashCode(ObjectValueImpl.java:178)
	at java.util.Objects.hashCode(Objects.java:98)
	at java.util.HashMap$Node.hashCode(HashMap.java:297)
	at java.util.AbstractMap.hashCode(AbstractMap.java:530)
	at org.openremote.model.value.impl.ObjectValueImpl.hashCode(ObjectValueImpl.java:178)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.containsKey(HashMap.java:596)
	at java.util.HashSet.contains(HashSet.java:204)
	at org.openremote.model.value.impl.ValueUtil$StringifyValueVisitor.checkCycle(ValueUtil.java:156)
	at org.openremote.model.value.impl.ValueUtil$StringifyValueVisitor.visit(ValueUtil.java:122)
	at org.openremote.model.value.impl.ObjectValueImpl.traverse(ObjectValueImpl.java:147)
	at org.openremote.model.value.impl.ValueVisitor.accept(ValueVisitor.java:85)
	at org.openremote.model.value.impl.ValueVisitor.accept(ValueVisitor.java:74)
	at org.openremote.model.value.impl.ValueUtil.stringify(ValueUtil.java:279)
	at org.openremote.model.value.impl.ValueUtil.stringify(ValueUtil.java:264)
	at org.openremote.model.value.impl.ValueUtil.stringify(ValueUtil.java:248)
	at org.openremote.model.value.impl.ObjectValueImpl.toJson(ObjectValueImpl.java:142)
	at org.openremote.model.asset.AbstractAssetUpdate.toString(AbstractAssetUpdate.java:374)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.openremote.manager.server.asset.AssetProcessingService.processAssetState(AssetProcessingService.java:319)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:57)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:298)
	at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:207)
	at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-12-20 15:31:23.082  WARNING [Messaging-AssetQueue-17       ] apache.camel.component.seda.SedaConsumer : Error processing exchange. Exchange[]. Caused by: [java.util.ConcurrentModificationException - null]
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at java.util.AbstractMap.hashCode(AbstractMap.java:530)
	at org.openremote.model.value.impl.ObjectValueImpl.hashCode(ObjectValueImpl.java:178)
	at java.util.Objects.hashCode(Objects.java:98)
	at java.util.HashMap$Node.hashCode(HashMap.java:297)
	at java.util.AbstractMap.hashCode(AbstractMap.java:530)
	at org.openremote.model.value.impl.ObjectValueImpl.hashCode(ObjectValueImpl.java:178)
	at java.util.Objects.hashCode(Objects.java:98)
	at java.util.HashMap$Node.hashCode(HashMap.java:297)
	at java.util.AbstractMap.hashCode(AbstractMap.java:530)
	at org.openremote.model.value.impl.ObjectValueImpl.hashCode(ObjectValueImpl.java:178)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.containsKey(HashMap.java:596)
	at java.util.HashSet.contains(HashSet.java:204)
	at org.openremote.model.value.impl.ValueUtil$StringifyValueVisitor.checkCycle(ValueUtil.java:156)
	at org.openremote.model.value.impl.ValueUtil$StringifyValueVisitor.visit(ValueUtil.java:122)
	at org.openremote.model.value.impl.ObjectValueImpl.traverse(ObjectValueImpl.java:147)
	at org.openremote.model.value.impl.ValueVisitor.accept(ValueVisitor.java:85)
	at org.openremote.model.value.impl.ValueVisitor.accept(ValueVisitor.java:74)
	at org.openremote.model.value.impl.ValueUtil.stringify(ValueUtil.java:279)
	at org.openremote.model.value.impl.ValueUtil.stringify(ValueUtil.java:264)
	at org.openremote.model.value.impl.ValueUtil.stringify(ValueUtil.java:248)
	at org.openremote.model.value.impl.ObjectValueImpl.toJson(ObjectValueImpl.java:142)
	at org.openremote.model.asset.AbstractAssetUpdate.toString(AbstractAssetUpdate.java:374)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.openremote.manager.server.asset.AssetProcessingService.processAssetState(AssetProcessingService.java:319)
	at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:120)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:113)
	at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:84)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:57)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:541)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:198)
	at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:298)
	at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:207)
	at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by christianbauer** [comment]
This part of the code was rewritten with GlobalLock usage.
