### ISSUE TITLE
Rules: Validity period is not applied to a rule

### ISSUE THREAD

**Issue by DonWillems** [openremote/openremote#793]
Reproduce:
- Create simple rule
- Add validity period (both repeating and one occurrence do not work) e.g. for a day next week, or in a few hours.
- Save rule
- See that rule activated anyway
- Error message shown in logs (see below, examples)

Expected:
- Rule only activates within validity period.

These logs show an error message 'Ruleset has invalid validity value 'Optional.empty'' right before there is a message 'Compiling ruleset deployment...' for a ruleset which has a specific validity period:
![Screenshot 2022-08-30 at 10 17 39](https://user-images.githubusercontent.com/11444149/187387735-ce0a3993-9e14-4087-96e1-71ce9fb8d0b9.png)
![Screenshot 2022-08-30 at 10 19 10](https://user-images.githubusercontent.com/11444149/187387758-bffd4966-bd3d-4b1b-99b0-589d4914e127.png)

**Comment by jvervier** [comment]
Hi,
Some more details from the manager logs :
`2022-08-31 09:23:56.224  SEVERE  [Messaging-PersistenceTop..c-30] org.openremote.manager.rules.RulesEngine : Ruleset has invalid validity value 'Optional.empty'
2022-08-31 09:23:56.231  INFO    [Messaging-PersistenceTop..c-30] org.openremote.manager.rules.RulesEngine : Compiling ruleset deployment: RealmRuleset{id='1007', version='0', name='qsdkjhqsd', lang='JSON', createdOn='Wed Aug 31 09:23:55 CEST 2022', lastModified='Wed Aug 31 09:23:55 CEST 2022', enabled='true', meta='{validity=MetaItem{name='validity', value='{start=1661934600000, end=1661936400000}'}}', realm='master', accessPublicRead='false'}
2022-08-31 09:23:56.264  SEVERE  [Messaging-PersistenceTop..c-30] org.openremote.manager.rules.RulesEngine : Ruleset compilation error: qsdkjhqsd
java.lang.IllegalArgumentException: Error building JSON rule when or then is not defined: qsdkjhqsd
        at org.openremote.manager.rules.JsonRulesBuilder.add(JsonRulesBuilder.java:632)
        at org.openremote.manager.rules.JsonRulesBuilder.<init>(JsonRulesBuilder.java:583)
        at org.openremote.manager.rules.RulesetDeployment.compileRulesJson(RulesetDeployment.java:270)
        at org.openremote.manager.rules.RulesetDeployment.compile(RulesetDeployment.java:219)
        at org.openremote.manager.rules.RulesEngine.addRuleset(RulesEngine.java:287)
        at org.openremote.manager.rules.RulesService.lambda$deployRealmRuleset$36(RulesService.java:699)
        at org.openremote.container.concurrent.GlobalLock.withLockReturning(GlobalLock.java:107)
        at org.openremote.manager.rules.RulesService.deployRealmRuleset(RulesService.java:680)
        at org.openremote.manager.rules.RulesService.lambda$processRulesetChange$32(RulesService.java:605)
        at org.openremote.container.concurrent.GlobalLock.lambda$withLock$0(GlobalLock.java:91)
        at org.openremote.container.concurrent.GlobalLock.withLockReturning(GlobalLock.java:107)
        at org.openremote.container.concurrent.GlobalLock.withLock(GlobalLock.java:90)
        at org.openremote.manager.rules.RulesService.processRulesetChange(RulesService.java:580)
        at org.openremote.manager.rules.RulesService.lambda$configure$2(RulesService.java:223)
        at org.apache.camel.processor.DelegateSyncProcessor.process(DelegateSyncProcessor.java:63)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:57)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.FilterProcessor.process(FilterProcessor.java:57)
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:548)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
        at org.apache.camel.processor.MulticastProcessor.doProcessParallel(MulticastProcessor.java:859)
        at org.apache.camel.processor.MulticastProcessor.access$200(MulticastProcessor.java:86)
        at org.apache.camel.processor.MulticastProcessor$1.call(MulticastProcessor.java:330)
        at org.apache.camel.processor.MulticastProcessor$1.call(MulticastProcessor.java:316)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)`

Working on it

**Comment by jvervier** [comment]
Issue is located on desieralization process as the MetaMap is the same as the one used initially for Asset.

A first clean solution is proposed to unblock the situation as soon as possible but a better separation between asset/ruleset should be done on code side for the deserialise.
